package Model;
// Generated 3 Aug, 2026 11:09:27 AM by Hibernate Tools 4.3.1



/**
 * Candidate generated by hbm2java
 */
public class Candidate  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int age;
     private String gender;
     private String mobile;
     private String email;
     private String party;
     private String symbol;
     private String photo;
     private String address;

    public Candidate() {
    }

    public Candidate(String name, int age, String gender, String mobile, String email, String party, String symbol, String photo, String address) {
       this.name = name;
       this.age = age;
       this.gender = gender;
       this.mobile = mobile;
       this.email = email;
       this.party = party;
       this.symbol = symbol;
       this.photo = photo;
       this.address = address;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getParty() {
        return this.party;
    }
    
    public void setParty(String party) {
        this.party = party;
    }
    public String getSymbol() {
        return this.symbol;
    }
    
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
}


