package Model;
// Generated 3 Aug, 2026 11:09:27 AM by Hibernate Tools 4.3.1



/**
 * Register generated by hbm2java
 */
public class Register  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String dob;
     private String mobile;
     private String email;
     private String password;
     private String voterId;
     private String photo;
     private String address;

    public Register() {
    }

    public Register(String name, String dob, String mobile, String email, String password, String voterId, String photo, String address) {
       this.name = name;
       this.dob = dob;
       this.mobile = mobile;
       this.email = email;
       this.password = password;
       this.voterId = voterId;
       this.photo = photo;
       this.address = address;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getVoterId() {
        return this.voterId;
    }
    
    public void setVoterId(String voterId) {
        this.voterId = voterId;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


